# Generated by Django 2.2.2 on 2019-07-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('fax', models.TextField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('road', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('no_customer', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('quantity', models.IntegerField(default='')),
                ('product_price', models.IntegerField()),
                ('supplier_price', models.IntegerField()),
                ('create_date', models.DateField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='Application.Brand')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('opening_balance', models.IntegerField()),
                ('opening_note', models.CharField(max_length=200)),
                ('opening_time', models.TimeField(default='')),
                ('closing_time', models.TimeField(default='')),
                ('expected', models.IntegerField(blank=True, default='0')),
                ('counted', models.IntegerField(blank=True, default='0')),
                ('difference', models.IntegerField(blank=True, default='0')),
                ('cash_payment_received', models.IntegerField(blank=True, default='0')),
                ('store_credit', models.IntegerField(blank=True, default='0')),
                ('total', models.IntegerField(blank=True, default='0')),
                ('closing_note', models.CharField(blank=True, default='Closing note', max_length=200)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('fax', models.TextField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('road', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('subtotal', models.IntegerField(default='')),
                ('tax', models.IntegerField(default='')),
                ('discount', models.IntegerField(default='')),
                ('items', models.IntegerField(default='')),
                ('amount_paid', models.IntegerField(default='')),
                ('paid', models.IntegerField(default='')),
                ('repay', models.IntegerField(default='')),
                ('customer_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sales_id', to='Application.Customer')),
                ('register_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sales_id', to='Application.Register')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saledetails_id', to='Application.Product')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saledetails_id', to='Application.Sales')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='Application.Supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='Application.Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='Application.Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='group_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='Application.Group'),
        ),
    ]
